#!/usr/bin/env python
import sys
import pexpect
import getpass
import time


# Username to be used in script
user= input("Username: ")

# Password to be used in script
p=getpass.getpass("Password: ")

# make the password with a carriage return
password = p + '\r'

# Here is a list of commands.  I'm unable to figure out how to deal with 
# Do you wish to continue [Y|N]
# This is a mixture of valid and invalid commands.  Future iterations should only have probable valid commands.
listOfCommands = ['Y\r', 
				'show system\r',
                'show access-port access-1-1-1-1\r',
                'show access-port access-1-1-1-2\r',
                        'show access-port access-1-1-1-3\r',
                        'show access-port access-1-1-1-8\r',
                        'show flow flow-1-1-1-1-1\r',
                        'show flow flow-1-1-1-1-6\r',
                        'logout\r']

with open('listOfIPs.txt') as IPAddresses:
        for IP in IPAddresses:
                # Create a dynamic file name composed of the CPE
                # and the time down to the second.
                IP = IP.strip()
                fileName = "CPE" + IP  + "TIME" + str(time.strftime('%m%d%Y%H%M%S'))

                # prepare ssh command without accepting keys with the provided username and password
                openHostCommand = "ssh -oStrictHostKeyChecking=no " + user + '@' + IP

                print(openHostCommand)
                # Open a ssh session to the IP address and send the password
                child = pexpect.spawn(openHostCommand)
                response = ""
                try:
                        response = child.expect(['assword: ', 'No route to host', '[Y|N]-->' ])
                except:
                        print("Failed to have feedback.")
                        continue;
                print(response)
                # Open a file handle based on CPE IP address and current time
                if response == 0:
                        child.sendline(password)
                        fout = open(fileName, 'wb')
                        child.logfile = fout
                # send commands to Adva from list of commands
                response = ""
                try:
                        response = child.expect(['-->'])
                except:
                        print("Took out do you wish to coninue part.")
                if response == 0:


                        child.sendline(password)
                        fout = open(fileName, 'wb')
                        child.logfile = fout
                # send commands to Adva from list of commands
                response = ""
                try:
                        response = child.expect(['-->'])
                except:
                        print("Took out do you wish to continue part.")
                if response == 0:
                        # run through the list of commands
                        print("I'm right above the command loop.")
                        for command in listOfCommands:
                                child.sendline(command + '\r')
                                print("sent " + command + '\r')
                                time.sleep(0.1)
                                child.expect('-->')
                # Move onto the next device.
                child.expect(pexpect.EOF, timeout=None)
                #close out the pexpect script.
                child.close()
                print("Reached closed.")
sys.exit()
